spring.application.name=DocuSenseApi

# ==========================================
# 1. PostgreSQL & JPA DataSource Configuration
# ==========================================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:docusense}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:mysecretpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# 2. OpenAI Configuration
# ==========================================
# spring.ai.openai.api-key=${OPENAI_API_KEY}
# spring.ai.openai.chat.options.model=gpt-4o-mini
# spring.ai.openai.embedding.options.model=text-embedding-3-small

# ==========================================
# Google Gemini Configuration
# ==========================================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash

# ==========================================
# 3. JWT Configuration
# ==========================================
app.jwt.secret=${JWT_SECRET:myDefaultSuperSecretKeyForJwtAuthentication123456}

# ==========================================
# 4. Spring AI Vector Store (pgvector)
# ==========================================
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.google.genai.embedding.text.dimensions=768
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# ==========================================
# 5. Redis Configuration (for Semantic Cache)
# ==========================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Enable detailed logging for Spring AI to see raw API requests/responses
logging.level.org.springframework.ai=DEBUG
